### ISSUE TITLE
version 0.3.9 npm install results in errors

### ISSUE THREAD

**Issue by Cybergo-at** [understrap/understrap-child#116]
Hi,

Noticed a new version was released, I've tried to use it and run an `npm install` but it results in errors when starting copy-assets.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/15031319/33473718-32f9598a-d680-11e7-817b-edb79855390b.png)

**Comment by mdemrs** [comment]
same issue here

**Comment by holger1411** [comment]
Thx for reporting. Was fixed here: https://github.com/holger1411/understrap/commit/0b06405a910e37ac7a938c4b8c2d2adf1c924305

Will be released with 0.6.10, but you can simply copy the latest gulpfile.js

**Comment by shansmith01** [comment]
Thanks @holger1411. I changed the gulp file but still get the issue.

**Comment by Cybergo-at** [comment]
@holger1411 Thanks for the fix. I've tried to copy the latest gulpfile.js as you recommended but the errors are still there :(

**Comment by shawncampbell** [comment]
@Cybergo-at Since understrap-child installs understrap v0.6.9 as a dependency during `npm install`, you won't be able to modify understrap's gulpfile.js before `npm post-install` runs `gulp copy-assets`. You could change package.json to downgrade understrap to 0.6.7 until 0.6.10 is released, or manually copy understrap 0.6.9 with the gulpfile.js patch into node_modules. There may be other ramifications of using 0.6.7, but it'll work for me as a workaround until 0.6.10 is available.

**Comment by shansmith01** [comment]
I can confirm that the update 0.6.10 has fixed this issue

**Comment by Thomas-A-Reinert** [comment]
Cannot reproduce that issue as of May 2018. Guess it has been solved then, as they were no further reports since December 2017.

Closing this issue for now. Feel free to reopen if the problem persists.
